common: fix yocto build issue
Sometimes the build fails because of fetch or setscene issues, so we try
another time

Example of error seen:
ERROR: libusb-compat-1_0.1.5-r0 do_package_qa_setscene: No suitable
staging package found

Running the petalinux-build command twice works